site_name: 黄晓宇的个人网站
site_url: https://doubleg258.github.io/mkdocs-site/
site_author: huangxiaoyu
theme:
  name: material
  features:
    - navigation.tabs  # 必须加！启用顶部横向导航栏
    - navigation.header: true  # 强制显示导航，避免折叠

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: white
      accent: light blue

     # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode 
      primary: black
      accent: light blue



nav:
  - 我:  
    - 个人介绍: ME/index.md
  - 计算机图形学: 
    - WEBGL/index.md
    - 实验一:
      - 任务 A: WEBGL/ch01/ch01html/task_a.html
      - 任务 B: WEBGL/ch01/ch01html/task_b.html
      - 任务 C: WEBGL/ch01/ch01html/task_c.html
      - 任务 D: WEBGL/ch01/ch01html/task_d.html
      - 任务 E: WEBGL/ch01/ch01html/task_e.html
    - 实验二:
      - 任务 A: WEBGL/ch02/ch02html/task_a.html
      - 任务 B: WEBGL/ch02/ch02html/task_b.html
      - 任务 C: WEBGL/ch02/ch02html/task_c.html
      - 任务 D: WEBGL/ch02/ch02html/task_d.html
      - 任务 E: WEBGL/ch02/ch02html/task_e.html
    - 实验三:
      - 任务 A: WEBGL/ch03/ch03html/ch.html
    - 实验四:
      - 任务 A,B,C: WEBGL/ch04/ch04html/ch04_1.html
      - 任务 E: WEBGL/ch04/ch04html/ch04_2.html
    - 实验五:
      - 任务 A: WEBGL/ch05/ch05html/Task_A.html
      - 任务 B: WEBGL/ch05/ch05html/Task_B.html
    - 实验六:
      - 任务 A: WEBGL/ch06/ch06html/ch06.html
    - 实验七:
      - 任务 A,B: WEBGL/ch07/ch07html/sphere-demo.html
      - 任务 C: WEBGL/ch07/ch07html/lab6-7-webgl.html
    - 网课笔记:
      - Lecture 2: WEBGL/NOTE/Lecture02.md
      - Lecture 3and4: WEBGL/NOTE/Lecture03and04.md
  - 关于我: aboutme.md
  - 联系我: contactme.md

markdown_extensions:
#添加图像配置
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
#-----------------------------
# 添加数学公式支持
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - mkdocs/javascripts/mathjax.js
#-----------------------------
# 添加灯箱插件
plugins:
   - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_themed: false
       auto_caption: false
       caption_position: bottom
       background: white
       shadow: true
       manual: false

# 启用搜索功能
   - search